runtime: python39

# instance: F2

entrypoint: waitress-serve --host 127.0.0.1 hello:app

env: standard

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /assets
  static_dir: assets

- url: /pages
  script: dashboard.projections
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto